name: videollama
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - pip:
      - flask
      - transformers>=4.31.0
      - accelerate>=0.21.0
      - bitsandbytes>=0.41.1
      - sentencepiece>=0.1.99
      - gradio>=3.40.1
      - decord>=0.6.0
      - einops>=0.6.1
      - fairscale>=0.4.13
      - webdataset>=0.2.48
      - pycocoevalcap>=1.2
      - opencv-python>=4.8.0.76
      - timm>=0.9.7
      - peft>=0.4.0
      - deepspeed>=0.10.0
      - tensorboardX>=2.6.2.2
      - av>=10.0.0
      - moviepy>=1.0.3